#
# Module manifest for module 'CredUICredential'
#
# Originally generated by: Zafer Balkan
#
# Fork maintained by: Alexander Marty
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule        = '.\CredUICredential\bin\Release\net10.0-windows\CredUICredential.dll'

    # Version number of this module.
    ModuleVersion     = '1.2.1.0'

    # Supported PSEditions
    # CompatiblePSEditions = @()

    # ID used to uniquely identify this module
    GUID              = '7d7d0c54-14b3-4f7d-9c4a-bc8673d62258'

    # Author of this module
    Author            = 'Alexander Marty'

    # Company or vendor of this module
    CompanyName       = 'Alexander Marty'

    # Copyright statement for this module
    Copyright         = '(c) 2026 Alexander Marty. Based on Get-WinCredential (c) 2022 Zafer Balkan. All rights reserved.'

    # Description of the functionality provided by this module
    Description       = 'Gets a credential object based on a user name and password. It uses Windows native dialogs even on PowerShell 7.x, instead of terminal. A maintained fork of the archived Get-WinCredential module by Zafer Balkan, with a fix for the modern-dialog password decryption bug.'

    # Minimum version of the PowerShell engine required by this module.
    # This is a binary module built for .NET 10, so it needs a host running on .NET 10:
    # PowerShell 7.6 is the first release that does.
    PowerShellVersion = '7.6'

    # Name of the PowerShell host required by this module
    # PowerShellHostName = ''

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @()

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport   = @('Get-CredUICredential')

    # Variables to export from this module
    VariablesToExport = '*'

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport   = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData       = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags         = @('windows', 'credential', 'credential-dialog', 'CredUI')

            # A URL to the license for this module.
            LicenseUri   = 'https://github.com/AlexCMarty/CredUICredential/blob/master/LICENSE.txt'

            # A URL to the main website for this project.
            ProjectUri   = 'https://github.com/AlexCMarty/CredUICredential'

            # ReleaseNotes of this module
            ReleaseNotes = 'https://github.com/AlexCMarty/CredUICredential/releases'

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    HelpInfoURI       = 'https://github.com/AlexCMarty/CredUICredential/blob/master/CredUICredential.md'

}
